### ISSUE TITLE
IOError at /translate/ubports/ubports-app/fi/

### ISSUE THREAD

**Issue by ghost** [ubports/translate.ubports.com#1]
Whenever I try to save a translated string, I receive the following error:

Request Method: | POST
-- | --
https://translate.ubports.com/translate/ubports/ubports-app/fi/?type=todo&offset=0
1.11.2
IOError
[Errno 13] Permission denied: u'/opt/weblate/data/vcs/ubports/ubports-app/po/fi.po'
/opt/weblate/lib/python2.7/site-packages/weblate/trans/formats.py in save, line 632
/usr/bin/python
2.7.12
['/opt/weblate/lib/python2.7/site-packages/weblate',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/opt/weblate/lib/python2.7/site-packages']
Sun, 27 Aug 2017 16:16:13 +0000

**Comment by Flohack74** [comment]
Please try again ;)

**Comment by ghost** [comment]
Works, thank you for fixing the permissions.

**Comment by Flohack74** [comment]
Unfortunately happens from time to time no idea ;)
weblate runs as www-data, but some jobs obviously as root

**Comment by NeoTheThird** [comment]
@Flohack74 Should we maybe report an upstream bug for that?

**Comment by Flohack74** [comment]
No its our "crappy" setup. This is how to make a business: Give the software as open source, but then it only runs well if you buy it hosted from them xD

**Comment by NeoTheThird** [comment]
Haha, ok. Do we need more helping hands / more expertise in this? If so we could maybe create a new issue to ask for additional maintainers and add the help wanted tag.
