### ISSUE TITLE
notes-app - untranslated - German

### ISSUE THREAD

**Issue by openlewa** [ubports/translate.ubports.com#5]
Please Fix. Thank you in advance.
![20200617_194347](https://user-images.githubusercontent.com/54738746/85176316-d86c8900-b279-11ea-8b5b-ce095263c7a6.jpg)

Choose minute selection mode for time picker: Use steps of [ ] 5min [ ] 1min = Wählen sie den Minutenauswahlmodus für die Zeitauswahl: Verwenden sie Schritte von [ ] 5min [ ] 1min

**Comment by Flohack74** [comment]
Please file this request here: https://gitlab.com/ubports/apps/notes-app/-/issues - The translation is not prepared correctly in the code it seems.
